### ISSUE TITLE
Product Show > Product Section Checklist

### ISSUE THREAD

**Issue by seadonggyun4** [seadonggyun4/TodayHouse-clone-project#1]
## Checklist

- Tab + TabPanel 구조
  - [ ] `aira-role` 을 사용해서 유기적으로 연결관계 유지
-공통 컴포넌트 분석후 제작
  - [ ] Tabpanel 내 헤더영역
    - [ ] 텍스트 only
    - [ ] 텍스트 + 뱃지 + 아이콘 링크
    - [ ] 텍스트 + 뱃지 + 텍스트 링크
    - [ ] 텍스트 + 뱃지 + 아이콘 버튼(드랍다운 스타일, 모바일 only)
  - [ ] Tabpanel 내 'table'
